// Generated by CoffeeScript 1.9.1
(function() {
  var fill, force, height, radius, svg, width;

  width = 1200;

  height = 900;

  radius = 6;

  fill = d3.scale.category20();

  force = d3.layout.force().gravity(.02).charge(-400).linkDistance(60).size([width, height]);

  svg = d3.select(".main").append('svg').attr("width", width).attr("height", height);

  d3.json('graph.json', function(error, graph) {
    var link, node, tick;
    if (error) {
      throw error;
    }
    console.dir(graph);
    link = svg.selectAll('line').data(graph.links).enter().append('line').style("stroke-width", function(d) {
      return d.value;
    });
    node = svg.selectAll('.node').data(graph.nodes).enter().append('g').attr("class", "node").call(force.drag);
    node.append("circle").attr('r', function(d) {
      return d.value;
    }).style('fill', function(d) {
      return fill(d.group);
    }).style('stroke', function(d) {
      return d3.rgb(fill(d.group)).darker();
    });
    node.append("text").attr("dx", 12).attr("dy", ".35em").text(function(d) {
      return d.name;
    });
    tick = function() {
      node.attr("transform", function(d) {
        return "translate(" + d.x + "," + d.y + ")";
      });
      return link.attr("x1", function(d) {
        return d.source.x;
      }).attr("y1", function(d) {
        return d.source.y;
      }).attr("x2", function(d) {
        return d.target.x;
      }).attr("y2", function(d) {
        return d.target.y;
      });
    };
    return force.nodes(graph.nodes).links(graph.links).on("tick", tick).start();
  });

}).call(this);

//# sourceMappingURL=graph.js.map
